/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxUserView: typeof import('./components/BoxUserView.vue')['default']
    BsIcon: typeof import('./components/BsIcon.vue')['default']
    CartDrawer: typeof import('./components/CartDrawer.vue')['default']
    copy: typeof import('./components/Test copy.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    MinimalShop: typeof import('./components/MinimalShop.vue')['default']
    MinimalShop_old: typeof import('./components/MinimalShop_old.vue')['default']
    ProductGrid: typeof import('./components/ProductGrid.vue')['default']
    ProductGrid_old: typeof import('./components/ProductGrid_old.vue')['default']
    ProductModal: typeof import('./components/ProductModal.vue')['default']
    ProductModal_copy: typeof import('./components/ProductModal_new.vue')['default']
    ProductModal_new: typeof import('./components/ProductModal_new.vue')['default']
    ProductModal_old: typeof import('./components/ProductModal_old.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
    TopBar_old: typeof import('./components/TopBar_old.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
  }
}
